### PR TITLE
Add Ffprobe support + Ffmpeg update + fdk-aac/libmp3lame/opus/ogg/vorbis libraries added

### PR DESCRIPTION
**Pull request by bertho-zero**

### CODE REVIEW

**Comment by rossmartin** [comment]
Thanks for this PR.  It looks like I'll need to add the new `FfprobeController.java` file to the plugin config.xml after integrating this.  Also will need to add docs for the `execFFPROBE` function.

The success callback to this `execFFPROBE` doesn't appear to be receiving any data back (https://github.com/bertho-zero/cordova-plugin-video-editor/blob/master/src/android/VideoEditor.java#L674)? Is the only information obtained sent to the progress callback function?

Won't there be a new ffprobe binary needed?

**Comment by rossmartin** [comment]
Ah nice I see the new binaries I missed them when I first looked at the changes.

**Comment by bertho-zero** [comment]
Where is the config.xml file which must contain the import of FfprobeController.java ?

The information arrives to the line at the time, the ideal shook all receive a single string at the end.

**Comment by rossmartin** [comment]
Looking it the plugin.xml it won't need to be updated to include the FfprobeController.java -

It includes the whole android-ffmpeg-java folder -

```
    <!-- android -->
    <platform name="android">
        <config-file target="config.xml" parent="/*">
            <feature name="VideoEditor">
                <param name="android-package" value="org.apache.cordova.videoeditor.VideoEditor" />
            </feature>
        </config-file>
        <!-- add android-ffmpeg-java lib -->
        <framework src="src/android/android-ffmpeg-java" custom="true" />
        <!-- add plugin class -->
        <source-file src="src/android/VideoEditor.java" target-dir="src/org/apache/cordova/videoeditor" />
    </platform>
```

Are you saying that on line 658 of VideoEditor.java that you will see the JSON output that can be sent back to the success function of `execFFPROBE`?  https://github.com/jbavari/cordova-plugin-video-editor/blob/master/src/android/VideoEditor.java#L658

**Pull request merged**
